version: "3.7"

services:

  frontend:
    image: supportchartfe:latest
    links:
      - backend:backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 80:80
      - 443:443

  backend:
    image: supportchartbe:latest
    ports:
      - "8080:8080"
    volumes:
      - ./webapp:/opt/webapp
